<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-12-17T11:33:13-03:00" hostname="https://mindful-fox-nzaknp-dev-ed.my.salesforce.com" tests="1" failures="1"  errors="0"  time="0.03">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Dec 17, 2020 11:33 AM"/>
            <property name="testExecutionTime" value="0.03 s"/>
            <property name="testTotalTime" value="0.03 s"/>
            <property name="commandTime" value="7.16 s"/>
            <property name="hostname" value="https://mindful-fox-nzaknp-dev-ed.my.salesforce.com"/>
            <property name="orgId" value="00D4x00000312ujEAA"/>
            <property name="username" value="henrique_nitatori@mindful-fox-nzaknp.com"/>
            <property name="testRunId" value="7074x000004qdy7"/>
            <property name="userId" value="0054x0000027d4KAAQ"/>
        </properties>
        <testcase name="accountDuplicateTest" classname="AccountRepositoryTest" time="0.03">
            <failure message="System.ListException: List index out of bounds: 2"><![CDATA[Class.FilterDuplicateAccountInList.filter: line 11, column 1
Class.AccountService.createAccount: line 16, column 1
Class.AccountRepositoryTest.accountDuplicateTest: line 29, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
